### ISSUE TITLE
Template for talks in January

### ISSUE THREAD

**Issue by dorksquith** [SussexMPhys2016/go#14]
If you want to do your presentation in powerpoint: 
[MPhys_Presentation_Template.pdf](https://github.com/SussexMPhys2016/go/files/609630/MPhys_Presentation_Template.pdf)

You can use this as a rough guide to the structure.

If you want to use latex beamer, which is what I used to generate the pdf above,
you can follow these steps:

1. Download this template file and then change the suffix from .txt to .tex [MPhys_Presentation_Template.txt](https://github.com/SussexMPhys2016/go/files/609591/MPhys_Presentation_Template.txt)

2. Download this figure so that you can compile the tex file: [wut.png](https://cloud.githubusercontent.com/assets/9458890/20572534/c028f9c6-b1a3-11e6-9d72-4e95676ac3b4.png)

3a. For mac users, you might have an existing Mactex installation. Or you can get [texshop](http://pages.uoregon.edu/koch/texshop/)
3b. For windows people, you can get [miktex](https://miktex.org/howto/install-miktex) and have a look at the [quickstart](https://docs.miktex.org/manual/localguide.html)

4. Build the talk, and skype/email me if you have probs.

**Comment by VeryAlienUser** [comment]
Closing this since the presentations are over
